#!/usr/bin/env python

import os
import sys

# GETTING-STARTED: change 'myproject' to your project name:
os.environ['DJANGO_SETTINGS_MODULE'] = 'myproject.settings'
# GETTING-STARTED: change 'myproject' to your project name:
sys.path.append(
    os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'myproject'))
virtenv = os.environ['APPDIR'] + '/virtenv/'
# GETTING-STARTED: make sure the next line has the right python version:
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv,
                                              'lib/python2.7/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

try:
    exec_namespace = dict(__file__=virtualenv)
    with open(virtualenv, 'rb') as exec_file:
        file_contents = exec_file.read()
    compiled_code = compile(file_contents, virtualenv, 'exec')
    exec(compiled_code, exec_namespace)
except IOError:
    pass

import django.core.wsgi

application = django.core.wsgi.get_wsgi_application()
